spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-aged-scene-aol2obai-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:npg_4MXkcWuhp5fn}
    driver-class-name: org.postgresql.Driver
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:supportscct@gmail.com}
    password: ${SMTP_PASSWORD:awyghkwkscztdypr}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
