spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/neondb}
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:npg_4MXkcWuhp5fn}
    driver-class-name: org.postgresql.Driver
  mail:
    host: ${SMTP_HOST:logging} # Uses console logger custom SMTP handler if set to logging
    port: ${SMTP_PORT:25}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
